# config/packages/cache.yaml
framework:
    cache:
        # Configuration du cache principal avec Redis
        app: cache.adapter.redis
        system: cache.adapter.system
        
        # Configuration Redis avec clustering et options avancées
        default_redis_provider: '%env(REDIS_URL)%'
        
        # Configuration Redis avancée
        redis:
            # Connexion principale
            default: '%env(REDIS_URL)%'
            # Connexion pour cache de session (peut être sur une DB différente)
            sessions: '%env(REDIS_SESSION_URL)%'
            # Connexion pour le cache de locks
            locks: '%env(REDIS_LOCKS_URL)%'
        
        # Pools de cache spécialisés avec stratégies optimisées
        pools:
            # Cache pour les calculs de prêts (long TTL car peu volatiles)
            cache.loan_calculations:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 3600  # 1 heure
                tags: true  # Support des tags pour invalidation ciblée
                
            # Cache pour les données utilisateur (TTL moyen)
            cache.user_data:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 1800  # 30 minutes
                tags: true
                
            # Cache pour les données KYC (long TTL car stables)
            cache.user_kyc:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 7200  # 2 heures
                tags: true
                
            # Cache pour les statistiques (TTL court car dynamiques)
            cache.statistics:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 300   # 5 minutes
                tags: true
                
            # Cache pour les métadonnées Doctrine
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 86400  # 24 heures
                
            # Cache pour les requêtes Doctrine
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 3600   # 1 heure
                
            # Cache pour les résultats Doctrine
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 1800   # 30 minutes
                
            # Cache pour les sessions (avec TTL configurable)
            cache.sessions:
                adapter: cache.adapter.redis
                provider: sessions
                default_lifetime: 3600   # 1 heure
                
            # Cache pour l'authentification et la sécurité
            cache.security:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 900    # 15 minutes
                tags: true
                
            # Cache pour l'API (rate limiting, etc.)
            cache.api:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 600    # 10 minutes
                tags: true
                
            # Cache pour les verrous distribués
            cache.locks:
                adapter: cache.adapter.redis
                provider: locks
                default_lifetime: 300    # 5 minutes
                
            # Cache pour le full-text search
            cache.search:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 1800   # 30 minutes
                tags: true
                
            # Cache pour les notifications
            cache.notifications:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 900    # 15 minutes
                tags: true
                
            # Cache pour les rapports et analytics (plus long TTL)
            cache.reports:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 7200   # 2 heures
                tags: true
                
            # Cache pour les templates et vues
            cache.templates:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 3600   # 1 heure
                
            # Cache pour les données externes (APIs tierces)
            cache.external_apis:
                adapter: cache.adapter.redis
                provider: default
                default_lifetime: 1800   # 30 minutes
                tags: true

when@prod:
    framework:
        cache:
            prefix_seed: 'loanmaster_%env(APP_VERSION)%'
            # Configuration optimisée pour la production
            pools:
                cache.loan_calculations:
                    # Stratégie de compression pour économiser la mémoire Redis
                    marshaller: 'cache.default_marshaller'
                cache.user_data:
                    marshaller: 'cache.default_marshaller'
                cache.statistics:
                    marshaller: 'cache.default_marshaller'
                cache.api:
                    # Cache API avec compression et sérialisation optimisée
                    marshaller: 'cache.default_marshaller'
                cache.reports:
                    # Compression forte pour les gros rapports
                    marshaller: 'cache.default_marshaller'
            
when@dev:
    framework:
        cache:
            # En dev, utiliser un mix Redis/Filesystem pour debug
            pools:
                cache.loan_calculations:
                    adapter: cache.adapter.redis
                    provider: default
                cache.user_data:
                    adapter: cache.adapter.redis  
                    provider: default
                cache.user_kyc:
                    adapter: cache.adapter.redis
                    provider: default
                cache.statistics:
                    adapter: cache.adapter.filesystem  # Debug plus facile
                cache.search:
                    adapter: cache.adapter.filesystem
                cache.templates:
                    adapter: cache.adapter.filesystem  # Templates en dev
                    
when@test:
    framework:
        cache:
            # Tests avec cache en mémoire pour isolation
            app: cache.adapter.array
            pools:
                cache.loan_calculations:
                    adapter: cache.adapter.array
                cache.user_data:
                    adapter: cache.adapter.array
                cache.user_kyc:
                    adapter: cache.adapter.array
                cache.statistics:
                    adapter: cache.adapter.array
                cache.search:
                    adapter: cache.adapter.array
                cache.notifications:
                    adapter: cache.adapter.array
                cache.reports:
                    adapter: cache.adapter.array
                cache.external_apis:
                    adapter: cache.adapter.array
                cache.api:
                    adapter: cache.adapter.array
                cache.security:
                    adapter: cache.adapter.array
