# config/packages/cache.yaml
framework:
    cache:
        # Configuration du cache principal
        app: cache.adapter.redis
        system: cache.adapter.system
        
        # Configuration Redis
        default_redis_provider: '%env(REDIS_URL)%'
        
        # Pools de cache spécialisés
        pools:
            # Cache pour les calculs de prêts (long TTL car peu volatiles)
            cache.loan_calculations:
                adapter: cache.adapter.redis
                default_lifetime: 3600  # 1 heure
                
            # Cache pour les données utilisateur (TTL moyen)
            cache.user_data:
                adapter: cache.adapter.redis
                default_lifetime: 1800  # 30 minutes
                
            # Cache pour les données KYC (long TTL car stables)
            cache.user_kyc:
                adapter: cache.adapter.redis
                default_lifetime: 7200  # 2 heures
                
            # Cache pour les statistiques (TTL court car dynamiques)
            cache.statistics:
                adapter: cache.adapter.redis
                default_lifetime: 300   # 5 minutes
                
            # Cache pour les métadonnées Doctrine
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 86400  # 24 heures
                
            # Cache pour les requêtes Doctrine
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 3600   # 1 heure
                
            # Cache pour les résultats Doctrine
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 1800   # 30 minutes
                
            # Cache pour les sessions (avec TTL configurable)
            cache.sessions:
                adapter: cache.adapter.redis
                default_lifetime: 3600   # 1 heure
                
            # Cache pour l'authentification et la sécurité
            cache.security:
                adapter: cache.adapter.redis
                default_lifetime: 900    # 15 minutes
                
            # Cache pour l'API (rate limiting, etc.)
            cache.api:
                adapter: cache.adapter.redis
                default_lifetime: 600    # 10 minutes

when@prod:
    framework:
        cache:
            prefix_seed: 'loanmaster_%env(APP_VERSION)%'
            
when@dev:
    framework:
        cache:
            app: cache.adapter.filesystem
            pools:
                cache.loan_calculations:
                    adapter: cache.adapter.filesystem
                cache.user_data:
                    adapter: cache.adapter.filesystem
                cache.user_kyc:
                    adapter: cache.adapter.filesystem
                cache.statistics:
                    adapter: cache.adapter.filesystem
                    
when@test:
    framework:
        cache:
            app: cache.adapter.array
            pools:
                cache.loan_calculations:
                    adapter: cache.adapter.array
                cache.user_data:
                    adapter: cache.adapter.array
                cache.user_kyc:
                    adapter: cache.adapter.array
                cache.statistics:
                    adapter: cache.adapter.array
