services:
    # Event Sourcing Infrastructure
    App\Infrastructure\EventSourcing\EventStore:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $tableName: 'event_store'
        tags:
            - { name: 'event_sourcing.event_store' }

    # Event Sourced Repositories
    App\Infrastructure\EventSourcing\Repository\LoanEventSourcedRepository:
        arguments:
            $eventStore: '@App\Infrastructure\EventSourcing\EventStore'
        tags:
            - { name: 'event_sourcing.repository' }

    # Event Handlers pour les projections
    App\Infrastructure\EventSourcing\EventHandler\LoanProjectionHandler:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
        tags:
            - { name: 'messenger.message_handler' }

    # Services d'audit
    App\Infrastructure\EventSourcing\AuditService:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $eventStore: '@App\Infrastructure\EventSourcing\EventStore'
        tags:
            - { name: 'event_sourcing.audit' }

    # Metrics Collector
    App\Infrastructure\EventSourcing\MetricsCollector:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $tableName: 'event_store_metrics'
        tags:
            - { name: 'event_sourcing.metrics' }

    # Command Bus pour Event Sourcing
    App\Infrastructure\EventSourcing\CommandBus:
        arguments:
            $messageBus: '@messenger.bus.default'
            $eventStore: '@App\Infrastructure\EventSourcing\EventStore'
            $auditService: '@App\Infrastructure\EventSourcing\AuditService'
            $metricsCollector: '@App\Infrastructure\EventSourcing\MetricsCollector'

    # Query Bus pour les projections
    App\Infrastructure\EventSourcing\QueryBus:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $metricsCollector: '@App\Infrastructure\EventSourcing\MetricsCollector'

    # Event Publisher
    App\Infrastructure\EventSourcing\EventPublisher:
        arguments:
            $messageBus: '@messenger.bus.default'
        tags:
            - { name: 'event_sourcing.publisher' }

    # Snapshot Store pour optimisation
    App\Infrastructure\EventSourcing\SnapshotStore:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $tableName: 'aggregate_snapshots'

    # Command Handlers
    App\Application\Command\Loan\CreateLoanApplicationHandler:
        arguments:
            $repository: '@App\Infrastructure\EventSourcing\Repository\LoanEventSourcedRepository'
            $snapshotStore: '@App\Infrastructure\EventSourcing\SnapshotStore'
        tags:
            - { name: 'messenger.message_handler' }
